### ISSUE TITLE
Add Test Demo

### ISSUE THREAD

**Issue by jiangtj** [JiangTJ/hexo-netlify-cms#1]

**Comment by jiangtj** [comment]
Add example, test can use this cmd, but it's not easy...
```
yarn link
cd example
yarn link hexo-netlify-cms
hexo s
```
maybe use another way to do it

**Comment by ivan-nginx** [comment]
So, as i see, it's online editor via Netlify for *.md files? Seems really good thing!

**Comment by jiangtj** [comment]
@ivan-nginx Yeah, it's a beautiful editor!
