### ISSUE TITLE
Suggestion to add Netlify build logs in Admin panel.

### ISSUE THREAD

**Issue by ivan-nginx** [JiangTJ/hexo-netlify-cms#5]
Like that: https://app.netlify.com/sites/theme-next/deploys

**Comment by jiangtj** [comment]
Emmm, It's provided by Netlify.
I just did a little to make it easier to use in hexo.
😂 
See: https://github.com/netlify/netlify-cms

**Comment by ivan-nginx** [comment]
How about to move `hexo-netlify-cms` under the NexT Org? And add it to the [Hexo Plugins](https://hexo.io/plugins/) list later?

**Comment by jiangtj** [comment]
Sorry, I don't want move it and add  it to the Hexo Plugins list.
Because it's only do little work.

**Comment by ivan-nginx** [comment]
And don't want to NexT Org?

**Comment by jiangtj** [comment]
> And don't want to NexT Org?

Any benefits for me or NexT Org?
It's not associated with NexT Theme. And I don't think NexT needs to include content that is not related to it.
